Verwalte SEPA-Lastschriftmandat
Naturseptime/qeddb-ruby pull request #8
Opened 2022-09-05 16:29 UTC by Nicholas42

Wir wollen ein Model für SEPA-Lastschriftmandate, das optional für jede Person ist und genau vom Kassier bearbeitet werden kann sowie genau vom Kassier und der Person selbst gesehen werden kann. Wir brauchen die Spalten für
* Mandatsreferenz (string), 
* "Tag an dem das Mandat unterschrieben wurde" (date), 
* IBAN (string), 
* BIC (string),
* Name des Kontoinhabers (string))

Ich habe mal versucht das zu implementieren, aber das bearbeiten geht noch nicht und ich habe ehrlich gesagt keine Ahnung, was ich tue.

2022-09-07 20:41 UTC, Nicholas42 commented
Ich konnte grade das komische Verhalten, wo es so wirkte, als wird das Mandat nicht immer gespeichert, debuggen. Es lag daran, dass das Mandat gelöscht wurde, immer wenn man es bearbeitete. Ich denke dieser PR ist jetzt soweit fertig.

Irgendwann sollten wir es noch ermöglichen, Zahlungen (für Mitgliedsbeiträge oder Seminarbeiträge) in bulk per upload zu verwalten (das würde dem Kassier das Leben vereinfachen). Aber ich deklariere das mal als out-of-scope für diesen PR.

2022-10-16 20:47 UTC, Nicholas42 commented
Ich habe jetzt noch was hinzugefügt, dass für Luke sehr gut wäre: Import von Kontoauszügen

2022-11-10 00:16 UTC, Naturseptime commented
hm ich bin etwas unglücklich drüber, dass der SEPA-Export nur "Export" heißt und dass beim Export anscheinend auch direkt Mails für den Einzug verschickt werden (Seiteneffekte)

2022-11-15 18:30 UTC, Naturseptime commented on app/controllers/events_controller.rb
> +		@registration_of_current_user = current_user.registrations.find_by(event: @event)
evtl. die Abfrage zumsammen mit edit_own_registration refactoren

2022-11-15 18:43 UTC, Naturseptime commented on app/models/event.rb
> +		if title.nil?
title sollte eigentlich nie nil sein

2022-11-15 19:21 UTC, Naturseptime commented on app/helpers/general_helpers.rb
> +		string.gsub(/[äöüß]/i) do |match|
Der Code wird bei mir (Ruby 3.0.4) eine Exception bei encode, anscheind buggt das irgendwas...
Dazu wird anscheiend das /i im Regex bei Umlauten nicht erkannt.
Ich würde vorschlagen, das komplette Replacement manuell zu machen

2022-11-15 21:32 UTC, Nicholas42 commented on app/policies/database_policy.rb
> +			:by_treasurer => [:import_banking_statement, :sepa_export]
Ich hatte es da rein, weil da auch das andere export war, aber ich sehe ein, dass man einfach ne BankingPolicy anlegen kann

2022-11-15 21:37 UTC, Nicholas42 commented on app/models/event.rb
> +		if title.nil?
Das tritt auf, wenn man die Veranstaltung grade anlegt, da `set_defaults` auf `after_initialize` aufgerufen wird, wird es auch aufgerufen, wenn das Erstellungsformular gerendert wird. (Ich bin in einen nil-Fehler hier reingelaufen)

2022-11-15 21:37 UTC, Nicholas42 commented on app/controllers/events_controller.rb
> +		@registration_of_current_user = current_user.registrations.find_by(event: @event)
In diesem PR oder ist das eine notiz für die Zukunft? (Die eigene Registrierung sollten wir ja eh mal ändern, damit der Anmeldeschluss nicht mehr alles blockiert).

2022-11-15 21:39 UTC, Nicholas42 commented on app/helpers/general_helpers.rb
> +		string.gsub(/[äöüß]/i) do |match|
Ich dachte wir sind noch auf Ruby2.7? Aber ich habe kein Problem das manuell zu machen. Meinst du damit, ohne Regex? (kenne nicht so die Möglichkeiten in Ruby)

2022-11-15 22:09 UTC, Naturseptime commented on app/helpers/general_helpers.rb
> +		string.gsub(/[äöüß]/i) do |match|
Ja auf dem Server ist Ruby2.7, aber es sollte halt trotzdem bei Ruby3 nicht kaputt gehen. Workaround:

`	def asciify(string)
		replacements = {
			'Ä' => 'Ae',
			'Ö' => 'Oe',
			'Ü' => 'Ue',
			'ẞ' => 'Ss',
			'ä' => 'ae',
			'ö' => 'oe',
			'ü' => 'ue',
			'ß' => 'ss'
		}
		string.gsub(/[^\p{ASCII}]/) do |match|
			replacements[match] || ''
		end
	end
`

2022-11-17 18:29 UTC, Naturseptime requested changes
Das Ändern von reference_line bei Events funktioniert nicht.
Außerdem sollte diese noch in der Übersicht angezeigt werden (falls man Kassier ist)

2022-11-17 18:29 UTC, Naturseptime commented on app/helpers/sepa_export_helper.rb
> +			sdd.add_transaction(
Hier kann es zu Exceptions kommen, wenn irgendwas an der Transaktion nicht stimmt (Mandat/IBAN ungültig)
Diese müssen angefangen werden, sonst gibts 503 in Production...

2022-11-17 18:33 UTC, Naturseptime commented
Ein Mockup für ein SEPA-Mandat zum Testen in test/fixtures wäre noch nice

2022-11-17 18:38 UTC, Naturseptime commented on app/helpers/banking_statement_import_helper.rb
> +			raise "Verwendungszweck enthält kein Trennzeichen."
Exceptions die geworfen werden, müssen behandelt werden, weil der User sonst nur 503 bekommt
=> rescue_from in ApplicationController

2022-11-17 21:32 UTC, Nicholas42 commented on app/helpers/banking_statement_import_helper.rb
> +			raise "Verwendungszweck enthält kein Trennzeichen."
Die sollten alle von dem rescue block in Zeile 129 gefangen werden.

2022-11-17 21:38 UTC, Nicholas42 commented
> Ein Mockup für ein SEPA-Mandat zum Testen in test/fixtures wäre noch nice

Werde ich bald hinzufügen.

2022-11-17 23:13 UTC, Naturseptime commented on app/controllers/sepa_export_controller.rb
> +			sepa_direct_debit = create_direct_debit to_use, execution_date
Wenn hier eine Exception passtiert, wird die Variable sepa_direct_debit garnicht gesetzt. Das fliegt dann später bei send_data um die Ohren

2022-11-20 15:49 UTC, Nicholas42 commented
> > Ein Mockup für ein SEPA-Mandat zum Testen in test/fixtures wäre noch nice
> 
> Werde ich bald hinzufügen.

Done

2022-11-25 22:25 UTC, Naturseptime commented on app/controllers/banking_statement_import_controller.rb
> +		@results = import_banking_csv(stream.read)
Ungültiges CSV wird nicht gecatcht

2022-11-25 22:28 UTC, Naturseptime commented on app/views/banking_statement_import/prepare.erb
> +          Diese muss sich im CSV-Format befinden und die Spalten "Verwendungszweck" und "Betrag" besitzen.</i>
CSV ist alles nur kein wohldefiniertes Format. Es sollten noch Sepatoren/Escaping-Rules dabei stehen

2022-11-25 22:33 UTC, Naturseptime commented on app/views/banking_statement_import/prepare.erb
> +        <%= file_field_tag 'import_file', {accept: 'application/json'} %>
hier sollte CSV statt JSON stehen

2022-11-25 22:34 UTC, Naturseptime commented on app/views/banking_statement_import/prepare.erb
> +          Diese muss sich im CSV-Format befinden und die Spalten "Verwendungszweck" und "Betrag" besitzen.</i>
Es sollte auch noch dabei stehen, in welchem Format Verwendungszweck steht

2022-11-25 22:40 UTC, Naturseptime commented on app/helpers/banking_statement_import_helper.rb
> +				raise "Keine Veranstaltung mit Namen #{name} gefunden."
name ist hier nicht deklariert (und bei "Multiple" ebenfalls nicht)

2022-11-25 22:57 UTC, Naturseptime commented on app/views/banking_statement_import/prepare.erb
> +          Diese muss sich im CSV-Format befinden und die Spalten "Verwendungszweck" und "Betrag" besitzen.</i>
Spalte "Buchungstag" wird auch benötigt

2022-11-25 23:10 UTC, Naturseptime commented on app/helpers/banking_statement_import_helper.rb
> +			unless registration.money_amount == amount
Hm, ich bin mal naiv und gehe davon, dass das keine Floating-Point-Precision-Probleme macht....

2022-11-25 23:13 UTC, Nicholas42 commented on app/helpers/banking_statement_import_helper.rb
> +			unless registration.money_amount == amount
Naja, das soll nur korrekt sein, wenn an beiden Stellen (im CSV und in der Veranstaltung) die gleiche Zahl steht. Ich hoffe mal ruby parst die gleichen strings zu den gleichen Zahlen. Floating-Point-Precision sollte nur ein Issue sein, sobald man damit rumrechnet, was wir nicht tun.

2022-11-25 23:13 UTC, merged